services:
  - type: web
    name: walmart-chatbot-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyA2XmTAncsUZogi6RFkS_oUCbgNIKe5Aaw
    autoDeploy: true

