# .streamlit/config.toml

[server]
# Increase timeout for model loading (useful for sentence-transformers)
maxUploadSize = 200
enableStaticServing = true
enableWebsocketCompression = true

# Memory settings
maxMessageSize = 200

[browser]
# Prevent the browser from trying to gather usage stats
gatherUsageStats = false

[theme]
# Optional: Set a custom theme
primaryColor = "#FF6B35"  # Walmart-ish orange
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
# Show error details (helpful for debugging)
showErrorDetails = true

# Toolbar mode
toolbarMode = "minimal"

[runner]
# Faster reruns
fastReruns = true

# Magic commands
magicEnabled = true